name: Lint Code Base

on:
  push:
    branches:
      - 'task/**'

    # Remove the line above to run when pushing to master
  pull_request:
    branches:
      - 'task/**'

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
        - uses: actions/checkout@v2
        - name: Super-Linter
          uses: github/super-linter@v3
