name: Lint Code Base

on:
  push:
    branches:
      - 'task/**'

    # Remove the line above to run when pushing to master
  pull_request:
    branches:
      - 'task/**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: pip install pylint

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          pylint: true

